root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/telegram"
cmd = "tailwindcss -i views/css/main.css -o public/styles.css && templ fmt . && templ generate && go build -tags dev -o ./tmp/telegram ."
delay = 20
exclude_dir = ["public", "tmp", "bin"]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
