[server]
listenAddr = ":3002"

[nats]
url = "nats://localhost:4222"
client = "json-client"
cluster = "json-cluster"

[subscription]
topic = "Telegram.Json"
queue = "tele-queue"

[timeouts]
server = "5s"
reconnect_wait = "5s"
close = "10s"
ack_wait = "5s"

[hasura]
endpoint = "http://localhost:8080/v1/graphql"
secret  = "aviation-test"